name: Main CI

on: [push, pull_request]

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Clippy Lints
        run: cargo clippy -- -D warnings
      - name: Run Tests
        run: cargo test
